package by.mustWork_01;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class FibonacciSequence {
    public int fiboSeq(int n) {
        if ((n == 1) || (n == 0)) {
            return n;
        }
        return fiboSeq(n - 1) + fiboSeq(n - 2);
    }

    public static void main(String[] args) {
        FibonacciSequence fibonacci = new FibonacciSequence();
        System.out.println(fibonacci.fiboSeq(8));
        // stackOverFlow
//        List list = Stream.iterate(2, (n) -> n + 1).filter(n -> n < 6).map(s -> fibonacci.fiboSeq(s)).collect(Collectors.toList());
//       System.out.println("fibonacci : "+list);
    }
}

